### ISSUE TITLE
Does not seem to accurately count startup time

### ISSUE THREAD

**Issue by TomBZombie** [kocsismate/php-di-container-benchmarks#11]
By the looks of it it uses a single PHP process. This means once a container's classes have been loaded via the autoloader, they are loaded for the rest of the tests. The startup time is only accounted for on the first test run, skewing the results and effectively removing the autoload time from the results.

Ideally a new PHP process should be launched for iteration of each test, otherwise the "startup time" isn't really valid, even moreso if any containers use global/static variables for caching. 

(Correct me if I'm wrong, I don't have PHP7.1 so can't trace through it)

**Comment by TomBZombie** [comment]
Take a look at this test for an example of how this comes into play:

https://rawgit.com/TomBZombie/php-dependency-injection-benchmarks/master/test6_results.html

If a container takes 1000ms to load/start and then 1ms to create each object, it'll be slower than a container that takes 200ms to load/start than 2ms to create each object...until a certain number of objects have been created.

**Comment by kocsismate** [comment]
I copied the method you used in your benchmark: each test is run 10 times (to gain some confidence), by creating a new process each time. Then in each test container startup is measured first, then it comes the main task which is repeated multiple times (iteration) in order to increate the time a test runs and to simulate some kind of pattern in production usage. So I think that you were wrong in your assumption about it, weren't you?

I have seen your benchmark (basically it gave me the inspiration to do mine) so I know why startup time is important and I also wanted to measure it. 

And I think you have a valid concern about that I not measured autoload time of the startup. I only decided to exclude it because I wanted to give possibility for containers to warm their caches first and this was the price of doing it. To resolve the issue I could eliminate cache warming for tests where startup time is included (you did the same if I am correct). Do you agree with this idea?

 What would you suggest?

**Comment by TomBZombie** [comment]
I did different things in different tests. Although this wasn't in the original article when I added more containers I added a sixth test which did mimic production. The initial reason I did this was Phalcon, it didn't really seem fair to let Phalcon load when the php binary loads and count the autoload time of the other containers. That said, the other tests still only really counted the autoload time the first loop around.

Take a look at https://github.com/TomBZombie/php-dependency-injection-benchmarks/blob/master/test6_runner.php

It's basically a "cold start" test as you'd get on a real website:  Connect -> Execute -> free memory -> repeat. There's no caching, no cached class loading (opcache is on as it would be in production). Containers that need to do complex instantiation need to be accounted for along with the time the autoloader needs to load all of the classes, your tests do not currently appear to do this. 

Ideally the "startup time" should be a "cold start" time as it better models a production server (that doesn't use a app server).

There is certainly a good reason to to have both benchmarks, but "startup time" without really counting autoloader and config load time isn't really meaningful.

**Comment by kocsismate** [comment]
Got it!

I don't plan to create a complete test case that tries to simulate a production environment completely, but changing the test runner to the following is a good move IMO:

```php
if ($isStartupTimeIncluded) {
    $t1 = microtime(true);
    $test->startup();
} else {
    // warmup
    $test->startup();
    $test->run();

    $t1 = microtime(true);
}

// Run tests
for ($i = 0; $i < $iterations; $i++) {
    $test->run();
}
$t2 = microtime(true);
```

**Comment by TomBZombie** [comment]
This still doesn't account for autoloader time though, once a class has been loaded via the autoloader it won't need to be loaded again and any DIC using static/global variables for caching will have a significant advantage. The only real test is launching a PHP process to simulate a request to the server.

**Comment by TomBZombie** [comment]
This doesn't really address the problem. This will add ONE startup time to all iterations, let's say there are 500 iterations and startup time is 1s, that's 1/500 additional time. Really to include startup time you need:

```
//make sure this is before any classes are autoloaded
  $t1 = microtime(true);
    $test->startup();
$t2 = microtime(true);

$startupTime = $t2 - $t1;

$totaltime = $averageTime + $startupTime
```

So the startup time is added to each iteration rather than divided among them all. However, it would still be more accurate to create a PHP process for each iteration. Even

```
for ($i = 0; $i < $iterations; $i++) {
    pctl_fork();
    $test->startup()
    $test->run();
}
```

would be better (although pctl_fork() might cause some odd behaviour, it would still be better to launch a php process with `exec()` )

**Comment by kocsismate** [comment]
I don't really get you now. This whole code is run as a separate process from the benchmark (https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Benchmark/Benchmark.php#L61)!

As I mentioned in my first comment, "runs" are for making confidence (https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Benchmark/Benchmark.php#L53), iterations are for simulating that a container is used multiple times in a single request (in my tests they range from 10 to 10 000) because in a `$test->run()` method there is only one fetch from the container (https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Container/Dice/Test1.php#L17).

**Comment by TomBZombie** [comment]
This still has the problem though. It spawns a PHP process, that PHP process then performs the benchmark with a set number of `$iterations`. Regardless of the number of iterations, the autoloader only runs once. 

The process is this:

Process is launched, Loop starts, Autoloader is triggered on first iteration, static caches are populated, On next iteration the autoloader is not necessary as all the classes have been loaded and static caches can be read.

This isn't really taking into account the startup time, to do so you'd need to factor in the startup time on each iteration:

```
for ($i = 0; $i < $iterations; $i++) {
$t1 = microtime(true);
 exec(
                PROJECT_ROOT . "/bin/test $number $containerName",
                $output,
                $code
            );
$t2 = microtime(true);
$iterationTimes[] = $t2 - $t1;
}
```

Then take an average of all `$iterationTimes`. 

At the moment, a container could take multiple seconds to load all it's files and the results array would look like this because the autoload time is only counted the first time the loop runs.

`[2.3456, 0.2345, 0.2467, 0.25679, 0.221895, ....]`

**Comment by TomBZombie** [comment]
At the moment your resultsets will look something like this:

```
['symfony' => [4.3456, 0.1345, 0.1467, 0.15679, 0.121895, ....],
 'dice' =>  [1.3456, 0.2345, 0.21467, 0.25679, 0.221895, ....]
]
```

Because the startup time is only factored into the first result, the numbers are highly skewed. Symfony creates the object graphs faster but takes considerably longer to load all its files/config.

**Comment by kocsismate** [comment]
Hey again,

I've refactored my test suite in major ways:

- tests are run on my host machine via PHP-FPM with OPcache enabled
- I implemented the 3 kinds of tests mentioned in the other issue: "cold" ones, "semi-warm" and "warm" ones
- I increased the number of measurements for each tests from 10 to 25 to get better accuracy

However, I'm still confused why you think the numbers are skewed, because the following happens for each __measurement__ (which is done 25 times per test):

- containers get autoloaded
- containers get bootstrapped
- entries are fetched 10/100/1000/10 000 times from containers (this is what I call iterations)
+1: on the first time, fetched objects are autoloaded

I believe you described the same method previously, but please tell me something if I am missing something.

Another important note that as soon as I properly put OPcache in place, startup times changed drastically, because there isn't much difference between let's say Symfony and Dice anymore (as I expected before). The original difference can be noticed only at the first measurement of the first test because the web server hasn't cached the OPcodes yet.

**Comment by TomBZombie** [comment]
The problem certainly existed in the last iteration of the code, where has the `exec` call been moved to in the new version? I searched the repo but couldn't find the `exec` call that used to be in `Benchmark.php`. 


From what you've said it looks like the problem has been accounted for, though.

**Comment by kocsismate** [comment]
the exec has been replaced by curl invocations here in the following class: https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Benchmark/WebBenchmarkContext.php (I originally created a separate class and interface because until yesterday, tests were also able to be run in CLI). And it is used here: https://github.com/kocsismate/php-di-container-benchmarks/blob/master/src/Benchmark/Benchmark.php#L85

But there wasn't any change in this logic maybe since my first commit (the `exec()` used to be almost in the same place: https://github.com/kocsismate/php-di-container-benchmarks/blob/7aeddaace82200060c8e19800497b6603b396c8a/src/Benchmark/Benchmark.php#L63).

**Comment by TomBZombie** [comment]
Thanks, that makes sense. My issue previously was that `$iterations` was a huge number that would effectively make any impact from startup time zero after taking an average. By using 10/100/1000/10000 the startup time can actually be seen.

I don't know how the opcache works internally but consider the following process:

- PHP process starts
- `$t1` is taken
- files are autoloaded

With the opcache, it's likely this happens:

- PHP process starts
- Opcache is loaded into the process
- `$t1` is taken


Depending on how the opcache works this could have an effect. 

To get the complete picture we'd really still need to do:

```php

$t1 = microtime(true);

        $ch = curl_init();
        curl_setopt(
            $ch,
            CURLOPT_URL,
            $this->benchmarkUrl . "?test_suite=$number&container=$container&iterations=$iterations&test_type=$testType"
        );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);
        return $output ? $output : "";

$t2 = microtime(true);
```

It's likely the difference is small, but

**Comment by kocsismate** [comment]
No, iteration numbers also didn't change for a long time!

I tried what you asked for but unfortunately I have to disagree that it is a good way to measure container performance:

Duration of network calls outweighed the duration of most tests (especially the ones with small iteration number) by at least an order of magnitude. That's why differences between containers became much smaller so it was really difficult to make any conclusions about container performance (especially after having seen Laravel DIC on the 2nd place in a test).

**Comment by TomBZombie** [comment]
Yeah unfortunately curl will add a significantly larger overhead than exec,
is there a reason for curl rather than exec?

That said, I calculated the overhead time by running the same benchmark on
a blank php script and subtracted it from all the tests.

**Comment by kocsismate** [comment]
I used curl because I wanted to minimize drift between the test environment and a possible production environment, mainly because I didn't know if opcache works as well in the CLI as on the web. I don't know if it was really a good move, but at least I do know that opcache works really well now. And the web interface is [really fancy](https://github.com/kocsismate/php-di-container-benchmarks/#usage-from-the-browser) too! :D

Yeah, I remember that you did that! But currently, I don't plan to introduce this measurement (I've got tired of pimping the benchmark because I worked too much on it in the last weeks) and I feel that this benchmark thorough enough for now - also thanks to your great insights!

**Comment by TomBZombie** [comment]
Yes, I think you're right. CLI opcache seems to be broken.  I tried the following settings:

```
opcache.enable=1
opcache.enable_cli=1

; When disabled, you must reset the OPcache manually or restart the
; webserver for changes to the filesystem to take effect.
opcache.validate_timestamps=0
```

That last setting *should* mean that the opcache isn't cleared until it's cleared manually. In reality, the following bash command should print `11`, in reality it prints `12` meaning the file is being parsed both times.

```
php -c ./ -r 'opcache_reset();' && echo '<?php echo 1;'  > test.php && php -c ./ test.php && echo '<?php echo 2;' > test.php && php -c ./ test.php

```
