### ISSUE TITLE
compare different DI container separately

### ISSUE THREAD

**Issue by drealecs** [kocsismate/php-di-container-benchmarks#16]
From my point of view, when comparing DI containers, you need to group them depending on what features they provide to their client. And I'm mostly talking about autowiring where I see 3 or more cases:
- full, no need to configure anything for a service
- require minimal configuration, as in symfony DI for example
- no support

This is because using autowire can speed up development while decreasing performance. So trade-offs must be understood correctly.

**Comment by kocsismate** [comment]
Sorry, I forgot to answer :/

I agree with you that results of different containers should be regarded separately. But I don't feel the need to emphasise this fact even more because I tried my best to do so in the introduction as well as in the conclusion.

Do you think it's worth emphasising it even more?

**Comment by garrettw** [comment]
I certainly do.
