### ISSUE TITLE
What made those containers unmaintained?

### ISSUE THREAD

**Issue by dominikzogg** [kocsismate/php-di-container-benchmarks#37]
Could you explain which criteria made them unmaintained?

https://github.com/kocsismate/php-di-container-benchmarks/commit/f071f6f137b6d2953c8a4b85dc048d488ce46393

Besides pimple (which is still heavily used) i cannot find any deprecations.

**Comment by kocsismate** [comment]
Hi,

I made this decision based on a few criterion:
- How long ago a container received maintenance
- How popular it is
- If it supports PHP 8
- If it supports PSR-11

Yeah, Pimple is heavily used, but since it's declaredly not maintained anymore for a long time now, I didn't bother with its migration to PHP 8.

Besides, I'm linking the other removed containers here with their last commit date and number of installs as of today:
- https://github.com/jshannon63/cobalt: 2018-04-17, 264
- https://github.com/bitExpert/disco: 2019-02-12, 1 643
- https://github.com/thecodingmachine/yaco: 2018-08-30, 319
- https://github.com/opulencephp/ioc: 2019-03-03, 657
- https://github.com/rdlowrey/auryn: 2019-02-19, 27 806

I even submitted https://github.com/thecodingmachine/yaco/issues/13 for Yaco a few months ago, but there was no response since then. So as it can be seen from this quick statistics, I only removed some not very popular containers which didn't receive any commit for more than 1,5 years (not even a "bump license year" one). A slight exception is Auryn, which is fairly popular, but I removed it any way, because it doesn't support PSR-11 at all, and it is now a requirement since the recent architectural changes of the benchmark (I'm currently changing the test suite for more meaningful tests).

**Comment by dominikzogg** [comment]
@kocsismate thanks for detailed explanation.

**Comment by kocsismate** [comment]
You're welcome!
